server:
  port: 8080
  tomcat.uri-encoding: UTF-8  
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    net841bc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"